icons_format = "{icon}"

[theme]
theme = "gruvbox-dark"
[theme.overrides]
# idle_bg = "#ff3456"
# idle_fg = "#dddddd"

[icons]
icons = "awesome4"
# [icons.overrides]
# bat = ["|E|", "|_|", "|=|", "|F|"]
# bat_charging = "|^| "

[[block]]
block = "net"
format = "$icon $bitrate "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "cpu"

[[block]]
block = "battery"

[[block]]
block = "memory"
format = " $icon  $mem_used.eng(w:3) $icon_swap $swap_used.eng(w:3) (z $zswap_decompressed.eng(w:3)) $zswap_comp_ratio:1"


[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "
